### ISSUE TITLE
Prettier config

### ISSUE THREAD

**Issue by ronvoluted** [danreeves/darkti.de#15]
We should add a formatting config. Don't mind which rules, just as long as we have them set. @danreeves @Wobin Let me know what you'd change to the below and I'll add the config:

```json
{
	"arrowParens": "always",
	"bracketSpacing": true,
	"printWidth": 120,
	"quoteProps": "consistent",
	"semi": true,
	"singleQuote": true,
	"tabWidth": 2,
	"trailingComma": "es5",
	"useTabs": true
}
```

**Comment by danreeves** [comment]
Already configured https://github.com/danreeves/darkti.de/blob/9b3b8dbb200a8e18c69a270f6df151e7b77d4750/package.json#L76

**Comment by ronvoluted** [comment]
Ah forgot. `"semi": false` is all we want?

**Comment by danreeves** [comment]
I like to keep config to a minimum, and avoiding bike shaving, but it also picks up using tabs from the .editorconfig

**Comment by ronvoluted** [comment]
What about `"printWidth": 120`?
