### ISSUE TITLE
Copy mission id button does nothing

### ISSUE THREAD

**Issue by AsheX1** [danreeves/darkti.de#31]
look for mission
press copy id

try pasting the random string for the missions nothing has bin put in the clipboard
so nothing gets pasted 
this keeps happing for 99% of the missions

im using firefox....

**Comment by AsheX1** [comment]
for the very few times it does work just make it output /mmtimport "mission string" so we don't have to keeo typing /mmtimport

**Comment by danreeves** [comment]
fixed in 8c26667eaf8bad429f948750af95544f7baa2c31
